### ISSUE TITLE
Task Hardcodes the Datadog endpoint to US.

### ISSUE THREAD

**Issue by alexevansigg** [billbatista/vsts-datadogevents#1]
Hey, Nice work on the task, I think you need to add a field to specify the API endpoint. 
I'm using the EU datadog instance and your task unfortunately has a hardcoded const defined for the US API.

**Comment by billbatista** [comment]
Hi!
Yes, this makes total sense and I should've made it like this since the beginning. I'm on vacation right now so can't look into it for a couple of days, but I believe next week is possible. Should be an easy fix.

I think the best approach is to have the US endpoint be the default but leave the field open to customization. Otherwise it would be a dropdown list of available endpoints but that would mean I'd have to update the task if Datadog decides to change the endpoint URI.

**Comment by alexevansigg** [comment]
Cool. But no rush on my behalf; I'm only evaluating datadog currently. On another note I actually have the use case to increment the azure.devops.event.count metric for each event I push... so I may fork your repo and have a tinker myself.

**Comment by Marcus-James-Adams** [comment]
Hi @billbatista , This would be lovely if it could be updated to support app.datadoghq.eu.
I thought I was going mad wondering where the notifications had gone to then realize it was pushing to the US.

**Comment by billbatista** [comment]
See #6
